# Setup
title:        Jan van der Vegt
tagline:      Machine Learning enthousiast blog
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Jan van der Vegt
  url:        http://janvdvegt.github.io 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
theme: jekyll-theme-cayman