# Setup
title:        Machine Teaching
tagline:      Machine Learning and more by Jan van der Vegt
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Jan van der Vegt
  url:        http://janvdvegt.github.io 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
theme: jekyll-theme-cayman