# Setup
title:        JvdV blog
tagline:      Jan van der Vegt - Machine Learning enthousiast
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Jan van der Vegt
  url:        http://janvdvegt.github.io 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
theme: jekyll-theme-cayman